lib/test/bootstrap.js
Small fix to prevent sandbox mess in the future.
=> Small Fix in Testing Hooks Using Sinon

lib/test/expect/expectError.js, test/integration/contract/DPContractFacade.spec.js, test/integration/contract/validateDPContractFactory.spec.js, test/integration/object/DPObjectFacade.spec.js, test/integration/object/validateDPObjectFactory.spec.js, test/integration/stPacket/STPacketFacade.spec.js, test/integration/stPacket/calculateItemsHash.spec.js, test/integration/stPacket/calculateItemsMerkleRoot.spec.js, test/integration/stPacket/validation/validateSTPacketFactory.spec.js, test/integration/stPacketHeader/STPacketHeaderFacade.spec.js, test/integration/stPacketHeader/validation/validateSTPacketHeaderFactory.spec.js, test/integration/util/entropy.spec.js, test/integration/util/merkleTree.spec.js, test/unit/DashPlatformProtocol.spec.js, test/unit/contract/DPContract.spec.js, test/unit/contract/DPContractFactory.spec.js, test/unit/contract/createDPContract.spec.js, test/unit/object/DPObject.spec.js, test/unit/object/DPObjectFactory.spec.js, test/unit/stPacket/STPacket.spec.js, test/unit/stPacket/STPacketFactory.spec.js, test/unit/stPacket/validation/findDuplicatedDapObjects.spec.js, test/unit/stPacket/validation/validateSTPacketDPContractsFactory.spec.js, test/unit/stPacket/validation/validateSTPacketDapObjectsFactory.spec.js, test/unit/stPacket/verification/fetchDPObjectsByObjectsFactory.spec.js, test/unit/stPacket/verification/verifyDPContractFactory.spec.js, test/unit/stPacket/verification/verifyDPObjectsFactory.spec.js, test/unit/stPacket/verification/verifySTPacketFactory.spec.js, test/unit/stPacketHeader/STPacketHeader.spec.js, test/unit/stPacketHeader/STPacketHeaderFactory.spec.js
~I'm too tired to wri..~ We're trying to have a more comprehensive test descriptions in our test suite.
Fixed assertions according to `chai` documentation.
Try and fix grammar in some of the test descriptions (kindly asking @dalibran to check my work)
Linter and test suite.
=> Fix Grammar in Tests

.travis.yml
As per https://github.com/travis-ci/travis-ci/issues/3897#issuecomment-101623421
=> Update Travis config file to build tags as well

package-lock.json, package.json
=> Set `dev` version and update `publishConfig`

schema/meta/data-contract.json, test/integration/dataContract/validateDataContractFactory.spec.js
=> feat: prevent of defining remote `$ref`

schema/meta/data-contract.json, test/integration/dataContract/validateDataContractFactory.spec.js
=> feat: prevent of defining `propertyNames` 

schema/meta/data-contract.json, test/integration/dataContract/validateDataContractFactory.spec.js
=> feat: ensure `maxItems` with `uniqueItems` for large non-scalar arrays

schema/meta/data-contract.json, test/integration/dataContract/validateDataContractFactory.spec.js
=> feat: ensure `maxLength` in case of `pattern` or `format`

lib/dataContract/DataContract.js, lib/dataContract/DataContractFactory.js, lib/dataContract/RawDataContractInterface.js, schema/dataContract/dataContractMeta.json, test/integration/dataContract/validateDataContractFactory.spec.js, test/unit/dataContract/DataContract.spec.js, test/unit/dataContract/DataContractFactory.spec.js
=> refactor: rename `$ownerId` to `ownerId` in Data Contract

README.md
Brings readme into [standard-readme](https://github.com/RichardLitt/standard-readme) compliance
N/A
N/A
=> docs: readme standard updates

lib/dataContract/validateDataContractFactory.js, lib/document/stateTransition/validation/data/validateDocumentsUniquenessByIndicesFactory.js, lib/test/fixtures/getDataContractFixture.js, lib/test/fixtures/getDocumentsFixture.js, test/unit/document/stateTransition/data/fetchDocumentsFactory.spec.js, test/unit/document/stateTransition/data/validateDocumentsUniquenessByIndicesFactory.spec.js
Add createdAt and updatedAt to system indices.
Fix error when the indexed field has an undefined value.
Tests
None
=> fix: error when the indexed field has an undefined value

package-lock.json, package.json
To make a pre-release we need to bump version
Bumped version to 0.14.0-dev.3
None
=> chore: bump version to 0.14.0-dev.3

package-lock.json, package.json
Updated `dashcore-lib` to `0.19.0`
Updated `dashcore-lib` to `0.19.0`
Tests.
None.
=> feat: update `dashcore-lib` to `0.19.0`

package-lock.json, package.json
Updating version for release.
Updated version for release.
None.
=> chore: bump version to `0.15.0-dev.1`

package-lock.json, package.json
Updated `dashcore-lib` to allow `dpp` to pass build
Updated `dashcore-lib` to allow `dpp` to pass build
Local build.
None.
=> feat: update `dashcore` to `0.19.1`

package-lock.json, package.json
Updated version for release.
Updated version for release.
None.
=> chore: bump version to `0.15.0-dev.3`

lib/test/fixtures/getDocumentsFixture.js, test/integration/document/Document.spec.js, test/integration/document/DocumentFacade.spec.js, test/integration/document/stateTransition/validation/data/executeDataTriggersFactory.spec.js, test/integration/document/stateTransition/validation/structure/validateDocumentsBatchTransitionStructureFactory.spec.js, test/integration/document/validateDocumentFactory.spec.js, test/integration/stateTransition/StateTransitionFacade.spec.js, test/integration/stateTransition/validation/validateStateTransitionStructureFactory.spec.js, test/unit/document/DocumentFactory.spec.js, test/unit/document/fetchAndValidateDataContractFactory.spec.js, test/unit/document/stateTransition/DocumentsBatchTransition.spec.js, test/unit/document/stateTransition/applyDocumentsBatchTransitionFactory.spec.js, test/unit/document/stateTransition/data/validateDocumentsBatchTransitionDataFactory.spec.js, test/unit/document/stateTransition/data/validateDocumentsUniquenessByIndicesFactory.spec.js, test/unit/document/stateTransition/structure/findDuplicatesByIndices.spec.js, test/unit/stateTransition/createStateTransitionFactory.spec.js, test/unit/stateTransition/validation/validateStateTransitionFeeFactory.spec.js
`getDocumentsFixture.dataContract` was not isolated properly
- `getDocumentsFixture` now accepts `dataContract`
Unit tests.
- `getDocumentsFixture.dataContract` is not available anymore
=> fix!: data contract fixture was not isolated properly

package-lock.json, package.json
Updated version for release
Updated version for release
None.
=> chore: bump version to `0.15.0-dev.4`

package-lock.json, package.json
=> chore: bump version to `0.15.0-dev.6`

lib/dataContract/enrichDataContractWithBaseSchema.js
"undefined" string in schema ID of enriched Data Contract for Document Transitions 
Set default value for `idPrefix` argument.
With tests
None
=> fix: undefined in data contract schema id

package-lock.json, package.json
=> chore: update version to 0.15.0-dev.7

package-lock.json, package.json
Updated version for a release
Updated version for a release
=> chore: bump version 0.15.0-dev.8

lib/dataTrigger/dpnsTriggers/createDomainDataTrigger.js, lib/document/stateTransition/documentTransition/AbstractDocumentTransition.js, lib/document/stateTransition/validation/data/validateDocumentsUniquenessByIndicesFactory.js, test/unit/dataTrigger/dpnsTriggers/createDomainDataTrigger.spec.js
A few bug fixes found during local testing.
- a `Buffer` is sent instead of `hex` in `createDomainDataTrigger`
- `InvalidQueryError` now added to `ValidationResult` in `validateDocumentsUniqueness`
Unit tests. Local dev env.
None.
=> fix: invalid where clause was sent, invalid query error was not handled by unique index validation method

package-lock.json, package.json
Updated version for a release
Updated version for a release
=> chore: update version to 0.15.0-dev.9

lib/document/stateTransition/validation/data/validateDocumentsUniquenessByIndicesFactory.js
Empty `where` conditions were sent in case of optional indexed fields
Filtered out empty where conditions
=> fix: empty where conditions were sent on unique indices validation

package-lock.json, package.json
=> chore: bump version to 0.15.0-dev.10

lib/dataTrigger/dpnsTriggers/createDomainDataTrigger.js, package-lock.json, package.json, test/unit/dataTrigger/dpnsTriggers/createDomainDataTrigger.spec.js
Need to check allowing subdomain rules for updated dpns contract
Updated dpns-contract to 0.3.0-dev.4
Added data trigger to check allowing subdomain rules
Unit tests
None
=> feat: add data trigger condition to check allowing subdomain rules

package-lock.json, package.json
Bumped version
Unit tests
None
=> chore: bump version to 0.15.0-dev.11

lib/dataTrigger/dpnsTriggers/createDomainDataTrigger.js, test/unit/dataTrigger/dpnsTriggers/createDomainDataTrigger.spec.js
Invalid arguments were submitted during search for a parent domain in `createDomainDataTrigger`
Updated arguments for `fetchDocuments`
Unit tests.
None.
=> fix: invalid arguments were submitted to search for parent domain

package-lock.json, package.json
=> chore: bump version to 0.15.0-dev.12

lib/dataTrigger/dpnsTriggers/createDomainDataTrigger.js, lib/test/fixtures/getDpnsDocumentFixture.js, test/unit/dataTrigger/dpnsTriggers/createDomainDataTrigger.spec.js
Subdomain registration rules were checked against currently created domain instead of it's parent domain
Only second-level domain owner is allowed to create its subdomains
=> fix!: subdomain rules were checked against subdomain instead of parent domain

package-lock.json, package.json
Bumped version
Unit tests
None
=> chore: bump version to 0.15.0-dev.13

CHANGELOG.md, package-lock.json, package.json
Release DPP 0.15
Changlog updated and version bumped to 0.15.0
None
None
=> chore(release): update changlog and bump version to 0.15.0

package-lock.json, package.json
Bumped version
Unit tests
None
=> chore: bump version to 0.16.0-dev.1

lib/identity/IdentityFactory.js, lib/identity/IdentityPublicKey.js, lib/test/fixtures/getIdentityCreateSTFixture.js, lib/test/fixtures/getIdentityFixture.js, schema/identity/publicKey.json, test/integration/identity/stateTransition/identityCreateTransition/validateIdentityCreateSTDataFactory.spec.js, test/integration/identity/validation/validatePublicKeysFactory.spec.js, test/unit/identity/Identity.spec.js, test/unit/identity/IdentityPublicKey.spec.js, test/unit/identity/stateTransitions/identityCreateTransition/IdentityCreateTransition.spec.js, test/unit/identity/stateTransitions/identityCreateTransition/validateAssetLockTransactionFactory.spec.js, test/unit/stateTransition/validation/validateIdentityExistenceFactory.spec.js
In order to follow the upcoming Identities DIP we need to remove outdated isEnabled property from Identity Public Key schema
isEnabled property removed from Identity Public Key schema
Unit tests
isEnabled property removed from Identity Public Key schema
=> feat!: isEnabled property removed from Identity Public Key

lib/identity/Identity.js, lib/identity/IdentityFactory.js, lib/identity/stateTransitions/identityCreateTransition/applyIdentityCreateTransitionFactory.js, lib/test/fixtures/getIdentityFixture.js, schema/identity/identity.json, test/integration/identity/validation/validateIdentityFactory.spec.js, test/unit/identity/Identity.spec.js, test/unit/identity/stateTransitions/identityCreateTransition/applyIdentityCreateTransitionFactory.spec.js
Revision property added to identity
Unit tests
No
=> feat: add revision property to identity

lib/identity/IdentityPublicKey.js, lib/stateTransition/AbstractStateTransitionIdentitySigned.js, schema/identity/publicKey.json, test/integration/identity/validation/validatePublicKeysFactory.spec.js
Introduced a BLS identity key type
Validate data property size according to the type
Unit tests
ECDSA Public key (type `0`) must be a base64 encoded string without padding and with a length of 44 symbols.
=> feat!: introduce a BLS identity key type

lib/identity/stateTransitions/identityCreateTransition/validateIdentityPublicKeysUniquenessFactory.js, test/unit/identity/stateTransitions/identityCreateTransition/validateIdentityPublicKeyUniquenessFactory.spec.js
Drive's `fetchIdentityIdsByPublicKeyHashes` not returns a list
Updated `validateIdentityPublicKeysUniqueness` to use lists
Unit tests.
None.
=> feat: Drive's `fetchIdentityIdsByPublicKeyHashes` not returns a list

package-lock.json, package.json
Bumped version
Unit tests
None
=> feat: bump version to 0.16.0-dev.2

lib/document/DocumentFactory.js, lib/test/fixtures/getDocumentsFixture.js, lib/test/fixtures/getDpnsDocumentFixture.js, lib/test/fixtures/getPreorderDocumentFixture.js, test/unit/document/DocumentFactory.spec.js
To prevent erroneous data submitted to `Document` constructor
Updated `DocumentFactory#create`
Unit tests.
None.
=> feat: validate document upon creation

package-lock.json, package.json
=> chore: bump version to 0.16.0-dev.4

lib/StateRepositoryInterface.js, lib/test/mocks/createStateRepositoryMock.js
Remove deprecated methods from StateRepositoryInterface
- removed `StateRepositoryInterface#fetchPublicKeyIdentityId` and `StateRepositoryInterface#storePublicKeyIdentityId`
- removed methods mentioned above from the mock
Run the tests
=> chore: remove deprecated state repository methods

package-lock.json, package.json
Dev version bump
Bumped dev version
None
=> chore(release): bump dev version

lib/document/Document.js, lib/document/stateTransition/documentTransition/DocumentCreateTransition.js, lib/document/stateTransition/documentTransition/DocumentReplaceTransition.js, lib/test/fixtures/getDocumentTransitionsFixture.js, test/unit/document/stateTransition/documentTransition/DocumentCreateTransition.spec.js
`DocumentCreateTransition#getEntropy` encoded as UTF-8 instead of base64 in `toJSON` method.
- Encoded entroy as base64 in `DocumentCreateTransition#toJSON` method.
- Added a test to cover `DocumentCreateTransition#toJSON`
With tests
None
=> fix: entropy encoded to UTF-8

lib/Identifier.js, test/unit/Identifier.spec.js
Identifier data couldn't be decoded by cbor
Changed the way how we encode Identifier data in CBOR
Tests
No
=> fix: identifier data couldn't be decoded by cbor

package-lock.json, package.json
Bumped version
Unit tests
None
=> feat: bump version to 0.16.0-dev.8

lib/document/stateTransition/validation/data/validateDocumentsUniquenessByIndicesFactory.js
Document ids were compared using `===` instead of `#equals`
Unit tests.
None.
=> fix: document IDs were incorrectly compared

CHANGELOG.md, package-lock.json, package.json, test/unit/dataTrigger/dpnsTriggers/createDomainDataTrigger.spec.js
Release DPP 0.16
- Updated changelog
- DPNS contract is updated to dev.6
- DashCore library is updated to 0.18.14
- Fixed `createDomainDataTrigger` tests
- Bumped version to 0.16
With tests
None
=> chore(release): update changelog and bump version to 0.16.0

package-lock.json, package.json
Need to update dashcore-lib to 0.19.5
dashcore-lib updated to 0.19.5
Tests
No
=> feat: update dashcore-lib to 0.19.5

webpack.config.js
fs not found error on deploy
Fixed webpack config
Local build
No
=> fix: fs not found error on deploy

package-lock.json, package.json
=> chore: bump version to `0.17.0-dev.3`

lib/identity/stateTransitions/assetLock/validateAssetLockStructureFactory.js, lib/test/fixtures/getAssetLockFixture.js, lib/test/fixtures/getIdentityCreateTransitionFixture.js, test/integration/identity/stateTransition/assetLock/validateAssetLockStructureFactory.spec.js
`verifyAssetLockProof` was receiving asset lock instead of proof
- used `.proof` property
- fixes to the fixture
Unit tests.
None.
=> fix: `verifyAssetLockProof` was receiving asset lock instead of proof

package-lock.json, package.json
=> chore: bump version to `0.17.0-dev.4`

lib/dataContract/DataContract.js, lib/document/fetchAndValidateDataContractFactory.js, lib/document/stateTransition/documentTransition/AbstractDataDocumentTransition.js, lib/document/stateTransition/documentTransition/DocumentReplaceTransition.js, lib/identity/stateTransitions/validateSignatureAgainstAssetLockPublicKeyFactory.js, lib/stateTransition/AbstractStateTransition.js, package-lock.json, package.json, schema/identity/identity.json, test/integration/identity/stateTransition/identityCreateTransition/validateIdentityCreateTransitionStructureFactory.spec.js, test/integration/identity/stateTransition/identityTopUpTransition/validateIdentityTopUpTransitionStructureFactory.spec.js, test/unit/dataContract/stateTransition/validation/validateDataContractCreateTransitionDataFactory.spec.js
In order to prevent users from creating identities with a large number of publicKeys keys this limits publicKeys to max 32
changed maxItems from 100 to 32
Unit tests and integration tests pass
This is a breaking change, as it limits an existing interface. But it shouldn't affect any existing integrations.
=> perf!: limit publicKeys items to 32

package-lock.json, package.json
=> chore(release): bump version to 0.17.0-dev.5

package-lock.json, package.json
Updating `dashcore-lib` with fixes for new quorum type in Core
Updating `dashcore-lib` with fixes for new quorum type in Core
=> feat: update `dashcore-lib` to `0.19.12`

package-lock.json, package.json
=> chore: update verion to 0.17.0-dev.6

package-lock.json, package.json
Update dashcore-lib to a version with `instalock.verify` fix
Run the tests
=> chore: update dashcore-lib version to v0.19.18

package-lock.json, package.json
=> chore(release): bump library version to 0.17.0-dev.9

package-lock.json, package.json
BLS library was throwing an error inside of the `uncaughtException` handler causing a Node process crash.
- updated `dashcore-lib`
Local runs
None.
=> fix: BLS was throwing an error inside `uncaughtException` handler

package-lock.json, package.json
Bump dev version
Bumped version
None
=> chore: bump version to 0.19.0-dev.1

README.md
Fix broken link in README.md
Use correct link
In browser
None
=> docs: fix docsify link

lib/dataTrigger/featureFlagsDataTriggers/createFeatureFlagDataTrigger.js, lib/test/fixtures/getFeatureFlagsContractFixture.js, lib/test/fixtures/getFeatureFlagsDocumentsFixture.js, package-lock.json, package.json, test/unit/dataTrigger/featureFlagDataTriggers/createFeatureFlagDataTrigger.spec.js
To be sure feature flag is not activated "in the past", additional check has been added
- updated `createFeatureFlagDataTrigger`
Unit tests
None.
=> fix: height check was missing in feature flag data trigger

CHANGELOG.md, package-lock.json, package.json
Release 0.19.0
- Update changelog
- Bump version to 0.19.0
None
None
=>  chore(release): update changelog and bump version 0.19.0

lib/dataTrigger/featureFlagsDataTriggers/createFeatureFlagDataTrigger.js, lib/dataTrigger/getDataTriggersFactory.js, package-lock.json, package.json, test/unit/dataTrigger/featureFlagDataTriggers/createFeatureFlagDataTrigger.spec.js
DocumentsBatchTransition failed to create documents due to `topLevelIdentity.getId is not a function` error in the corresponding Data Trigger. Also, Data Triggers weren't attached to `verifyLLMQSignaturesWithCore` document type.
- Add `verifyLLMQSignaturesWithCore` feature flag
- use `topLevelIdenity` as `Identifier`
None
=> fix: `topLevelIdentity.getId` is not a function

package-lock.json, package.json
re2-wasm updated to v.1.0.4
No
=> fix: re2-wasm process exit error

package-lock.json, package.json
Bumping version before release
Bumped version
None.
=> chore: bump version to 0.20.0-dev.3

lib/dataTrigger/getDataTriggersFactory.js
Removing VERIFY_LLMQ_SIGS_WITH_CORE feature flag data triggers, as this feature flag is being removed in drive v20. For more details, please refer to Drive PRs:
dashevo/js-drive#533
dashevo/js-drive#536
Removed data triggers that were depending on the removed feature flag
Makes previously existing data triggers not existing anymore
=> feat: remove verify SML flag triggers

lib/dataContract/DataContract.js, lib/dataContract/DataContractFactory.js, lib/document/Document.js, lib/document/DocumentFactory.js, lib/identity/Identity.js, lib/identity/IdentityFactory.js, lib/protocolVersion.js, test/integration/dataContract/stateTransition/validation/validateDataContractCreateTransitionStructureFactory.spec.js, test/integration/document/stateTransition/validation/structure/validateDocumentsBatchTransitionStructureFactory.spec.js, test/unit/dataContract/DataContractFactory.spec.js, test/unit/dataContract/stateTransition/DataContractCreateTransition.spec.js, test/unit/document/Document.spec.js, test/unit/document/stateTransition/applyDocumentsBatchTransitionFactory.spec.js, test/unit/identity/Identity.spec.js, test/unit/identity/stateTransitions/identityCreateTransition/IdentityCreateTransition.spec.js, test/unit/identity/stateTransitions/identityCreateTransition/applyIdentityCreateTransitionFactory.spec.js
Need to stop using different protocol versions (use single one instead).
Replaced separate protocol versions in `Document`, `Identity`, and `DataContract` with the single one.
No
=> feat: use only one protocol version in DPP

CHANGELOG.md
Breaking features list was incomplete. 0.20 didn't mention the need to call `initialize` (added in https://github.com/dashevo/js-dpp/pull/311/commits/f5dced870af29f1ebd4d9145a815cc3f25bb1314)
Added missing item
N/A
N/A
=> docs: add missing breaking feature to changelog

lib/DashPlatformProtocol.js, lib/dataContract/DataContractFacade.js, lib/dataContract/DataContractFactory.js, lib/document/DocumentFacade.js, lib/document/DocumentFactory.js, lib/identity/IdentityFacade.js, lib/identity/IdentityFactory.js, lib/stateTransition/StateTransitionFacade.js, lib/test/fixtures/getDashPayContractFixture.js, lib/test/fixtures/getDashPayDocumentFixture.js, lib/test/fixtures/getDataContractFixture.js, lib/test/fixtures/getDocumentTransitionsFixture.js, lib/test/fixtures/getDocumentsFixture.js, lib/test/fixtures/getDpnsContractFixture.js, lib/test/fixtures/getDpnsDocumentFixture.js, lib/test/fixtures/getFeatureFlagsContractFixture.js, lib/test/fixtures/getFeatureFlagsDocumentsFixture.js, lib/test/fixtures/getPreorderDocumentFixture.js, lib/test/mocks/createDPPMock.js, test/integration/DashPlatformProtocol.spec.js, test/integration/dataContract/DataContractFacade.spec.js, test/integration/stateTransition/StateTransitionFacade.spec.js, test/unit/DashPlatformProtocol.spec.js, test/unit/dataContract/DataContractFactory.spec.js, test/unit/document/Document.spec.js, test/unit/document/DocumentFactory.spec.js, test/unit/document/stateTransition/DocumentsBatchTransition.spec.js, test/unit/identity/IdentityFactory.spec.js, test/unit/stateTransition/validation/validateStateTransitionDataFactory.spec.js, test/unit/stateTransition/validation/validateStateTransitionStructureFactory.spec.js
Adding an ability to pass external `protocolVersion` as an option
- added `protocolVersion` 
- added setter for it
Unit tests
None
=> feat: add `protocolVersion` option to DPP class

package-lock.json, package.json
The unused `@dashevo/drive-grpc` dependency on a deprecated package was requiring `grpc`, another deprecated package which we are attempting to remove from all platform repos to improve build times. Fixes #332.
Removed:
- `@dashevo/drive-grpc`
- `lodash.mergewith`
- With `npm run test`
- In CI
=> chore: remove grpc and unused deps from package

package-lock.json, package.json
Warnings during build `More than one instance of dashcore-lib found.`
Update `dashcore-lib` to latest version to match compatible repos
In CI
None
=> chore: update dashcore-lib dep

lib/dataContract/DataContract.js, lib/decodeProtocolEntityFactory.js, lib/document/Document.js, lib/identity/Identity.js, lib/stateTransition/AbstractStateTransition.js, test/unit/dataContract/DataContract.spec.js, test/unit/dataContract/stateTransition/DataContractCreateTransition/DataContractCreateTransition.spec.js, test/unit/decodeProtocolEntityFactory.spec.js, test/unit/document/Document.spec.js, test/unit/document/stateTransition/DocumetsBatchTransition/DocumentsBatchTransition.spec.js, test/unit/identity/Identity.spec.js
Updated `protocol version` encoding and decoding to use little-endian
- `_UInt32BE` to `_UInt32LE`
Unit tests.
- ???
=> feat: change protocol version encoding from big-endian to little-endian

lib/dataContract/DataContractFactory.js, lib/document/DocumentFactory.js, lib/identity/IdentityFactory.js, lib/stateTransition/StateTransitionFacade.js, lib/stateTransition/StateTransitionFactory.js, test/unit/dataContract/DataContractFactory.spec.js, test/unit/decodeProtocolEntityFactory.spec.js, test/unit/document/DocumentFactory.spec.js, test/unit/identity/IdentityFactory.spec.js, test/unit/stateTransition/StateTransitionFactory.spec.js
Some cleanup after protocol version validation changes
- Remove unnecessary arguments from calls
None
=> refactor: cleanup after protocol validation changes

.github/workflows/test_and_release.yml, package-lock.json
We need to update to node 16
- Update package to node 16
- Run tests
- Update CI
In CI
None
=> chore: update package to node 16

lib/version/protocolVersion.js
Revert temporary protocol version to 1 before we fix the bug
- Revert protocol version to 1
With tests
None
=> chore: revert protocol version

lib/errors/consensus/basic/UnsupportedProtocolVersionError.js, lib/version/validateProtocolVersionFactory.js, test/unit/version/validateProtocolVersionFactory.spec.js
validateProtocolVersion works incorrectly
Fxied validateProtocolVersion method
With tests
No
=> fix: validate protocol version

lib/version/protocolVersion.js
Add temporary protocol version 2 to conduct a test on the upgrade process.
- Bump protocol version to 2
With tests
None
=> chore: bump temporary protocol version

lib/test/fixtures/getInstantAssetLockProofFixture.js, package-lock.json, package.json
Update dashcore-lib to 0.19.27
Update test InstantLock fixture
With tests
Will not work with DashCore < 0.18.0
=> feat!: update dashcore-lib to 0.19.27
