dashevo/js-dpp

README.md

The NPM badge is dependent on an actual publish being done first, so will need #4 merged and to verify the deployment to NPM.

Fix build badge and add NPM version badge

---

README.md
webpack.config.js

* Update link to js-dpp repo issues
* Change name of DPP identifier in bundle
If my understanding is correct (I could quite possibly be wrong), the current
name w/a hyphen would not allow this to be used easily in a browser, whereas
DashPlatformProtocol is completely valid as a library name.

Update library name in 2 missed places

---

package-lock.json
package.json

@shumkov @antouhou It seems NPM does not want to publish `0.8.0` over `0.8.0-dev*` branches somehow. [Telling it is already published](https://travis-ci.com/dashevo/js-dpp/jobs/248168294). Close this PR if I'm missing something.

Update to `0.8.1`

---

lib/dataTrigger/DataTrigger.js
lib/dataTrigger/dpnsTriggers/createDomainDataTrigger.js
lib/dataTrigger/dpnsTriggers/deleteDomainDataTrigger.js
lib/dataTrigger/dpnsTriggers/updateDomainDataTrigger.js
lib/errors/AbstractDataTriggerError.js
lib/errors/DataTriggerConditionError.js
lib/errors/DataTriggerExecutionError.js
lib/errors/DataTriggerInvalidResultError.js
package-lock.json
package.json
test/unit/dataTrigger/DataTrigger.spec.js
test/unit/document/stateTransition/data/validateDocumentsSTDataFactory.spec.js

Context is to big to pass it whole into GRPC metadata. Let's simplify errors by providing only data we need from the context.

feat: update data trigger errors

---

lib/dataContract/validateDataContractFactory.js
lib/errors/UniqueIndicesLimitReached.js
package-lock.json
schema/meta/data-contract.json
test/integration/dataContract/validateDataContractFactory.spec.js

BREAKING CHANGE:
- Number of indices limited to 10
- Number if unique indices limited to 3
- Number of properties in an index limited to 10

feat: limit number of document indices

---

schema/meta/data-contract.json
test/integration/dataContract/validateDataContractFactory.spec.js

BREAKING CHANGE: `properties` and `additionalProperties` are required for objects

feat: ensure all object properties are defined

---

schema/meta/data-contract.json
test/integration/dataContract/validateDataContractFactory.spec.js

BREAKING CHANGE: `items` and `additionalItems` are required for arrays

feat: ensure all arrays items are defined

---

lib/dataContract/enrichDataContractWithBaseSchema.js
lib/dataContract/validateDataContractFactory.js
lib/document/stateTransition/validation/structure/validateDocumentsBatchTransitionStructureFactory.js
lib/document/validateDocumentFactory.js

Enriching data contracts with various document base schemas we use the same contract schema id that's lead to using previously cached schemas in AJV instead of enriched one.
Introduced id prefix to `enrichDataContractWithBaseSchema` that now responds with the `DataContract` model instead of raw data. 
None

fix: conflicting schema ids in AJV cache

---

schema/dataContract/dataContractMeta.json

Some Data Contract rules like strict property definitions and index properties validation don't handle JSON Schema conditions properly, so we disable them temporarily until we fix it.
Removed JSON Schema conditions from document schema definition.
With unit tests.
JSON Schema conditions are not allowed anymore.

feat!: disable unsupported JSON Schema conditions

---

lib/dataContract/validateDataContractFactory.js
lib/errors/InvalidIndexedPropertyConstraintError.js
lib/errors/MissingIndexedPropertyConstraintError.js
lib/test/fixtures/getDataContractFixture.js
test/integration/dataContract/validateDataContractFactory.spec.js

We need to validate indexed string properties for `maxLength` constraint. As we have constraints for those field values in `Drive` as well.
Added validation of `maxLength` constraint for indexed string properties.
Tests.
- Indexed string properties should now have `maxLength` constraint set of maximum `1024` characters.

fix: missing indexed string property constraint validation

---

lib/document/validateDocumentFactory.js
test/integration/document/validateDocumentFactory.spec.js

When calling second-time `validateDocument` it throws `schema with key or id ... already exists` error
Set correct schema ID to the `additionalSchemas` validator param.
None

fix: schema with key or id already exists

---

lib/document/Document.js
lib/document/stateTransition/documentTransition/AbstractDocumentTransition.js
lib/test/fixtures/getDataContractFixture.js
lib/test/fixtures/getDocumentsFixture.js
schema/dataContract/dataContractMeta.json
test/integration/document/Document.spec.js
test/integration/document/validateDocumentFactory.spec.js
test/unit/dataContract/DataContract.spec.js
test/unit/dataContract/getEncodedPropertiesFromSchema.spec.js

Binary fields were encoded using `utf-8` which is not enough for some cases.
- Binary fields now encoded using `base64`
Unit tests.
`contentEncoding` field for binary data now should be `base64` instead of `binary`

fix!: binary fields encoded using `utf-8` are loosing data 

---

lib/document/Document.js
lib/document/DocumentFactory.js
lib/stateTransition/AbstractStateTransition.js
lib/stateTransition/StateTransitionFactory.js
test/unit/document/DocumentFactory.spec.js
test/unit/document/stateTransition/DocumentsBatchTransition.spec.js
test/unit/stateTransition/StateTransitionFactory.spec.js

We should use plain object for CBOR to correctly encode and decode those
- passing plain object to `encode` function
- using `createFromObject` in `createFromSerialized`
Unit tests
- `Document#serialize` now returns CBOR encoded plain object instead of CBOR encoded  JSON
- `Document#dash` now will be different

feat!: encode and decode plain object document instead of JSONs

---

lib/dataContract/validateDataContractFactory.js
lib/document/stateTransition/validation/data/validateDocumentsBatchTransitionDataFactory.js
lib/document/stateTransition/validation/data/validatePartialCompoundIndices.js
lib/errors/InconsistentCompoundIndexDataError.js
lib/errors/InvalidCompoundIndexError.js
lib/errors/InvalidIndexDefinitionError.js
lib/stateTransition/StateTransitionFacade.js
lib/test/fixtures/getDataContractFixture.js
lib/test/fixtures/getDocumentsFixture.js
test/integration/dataContract/validateDataContractFactory.spec.js
test/integration/document/Document.spec.js
test/integration/document/validateDocumentFactory.spec.js
test/unit/document/stateTransition/data/validateDocumentsBatchTransitionDataFactory.spec.js
test/unit/document/stateTransition/data/validatePartialCompoundIndices.spec.js

Duplicate key error in case of unique index on optional fields
Additional index validators were added
Unit tests
A document compound unique index shouldn't contain both required and optional properties.
A document with a compound unique index must contain all indexed properties or non of them. 

fix!: duplicate key error in case of unique index on optional fields

---

lib/stateTransition/StateTransitionFactory.js
test/unit/stateTransition/StateTransitionFactory.spec.js

Creating a new document with an unknown type will throw `InvalidDocumentTypeError` instead of `InvalidStateTransitionError` containing this error.
The `createFromObject` method was modified to handle consensus errors from the `toJSON` method
Unit tests
No

fix: `stateTransition.toJSON` throws an error

---

schema/identity/identity.json
schema/identity/stateTransition/identityCreate.json
test/integration/identity/validation/validateIdentityFactory.spec.js
test/integration/stateTransition/validation/validateStateTransitionStructureFactory.spec.js

We need to make sure that identity and identity create transition do not contain duplicate keys
uniqueItems keywords were added to identity and identityCreate schemas
Unit tests
identity and identityCreate schemas can't contain duplicate public keys anymore

feat!: identity public keys must be unique within particular Identity

---

lib/test/fixtures/getDataContractFixture.js
schema/dataContract/dataContractMeta.json
test/unit/document/Document.spec.js

Base 64 required `pattern` allows an empty string that doesn't make sense since `maxLength` is a required keyword while using the `pattern` keyword.
Chars length operator for Base 64 content encoding required pattern is changed from `*` to `+`
With tests
Base64 now requires a `pattern` keyword equals to `^([A-Za-z0-9+/])+$`

fix!: base64 pattern allow empty string

---

lib/ajv/keywords/byteArray/addByteArrayKeyword.js
lib/ajv/keywords/byteArray/byteArray.js
lib/ajv/keywords/byteArray/maxBytesLength.js
lib/ajv/keywords/byteArray/minBytesLength.js
test/integration/ajv/keywords/byteArray/addByteArrayKeyword.spec.js

Definition and validation of binary data pretty complicated and confusing due to using encoded string. In case if a user needs `minLength`/`maxLength` constraints, they should be calculated for result encoded string but not an origin byte array length. Also, during validation, it required to convert raw data to JSON data (encode Buffers to string) that adds additional complexity and slowdown the consensus eventually.
Added `byteArray`, `minBytesLength`, and `maxBytesLength` keywords to Ajv, so they can be added later to the data contract meta schema and used in other protocol JSON schemas. `minBytesLength` and `maxBytesLenth` are optional and must be used only together with `byteArray` keyword. `byteArray` must be used only with schema type `object`.
```json
{
"properties": { …
```

feat: `byteArray` JSON Schema keyword

---

lib/StateRepositoryInterface.js
lib/identity/stateTransitions/identityCreateTransition/applyIdentityCreateTransitionFactory.js
lib/identity/stateTransitions/identityCreateTransition/validateIdentityCreateTransitionDataFactory.js
lib/identity/stateTransitions/identityTopUpTransition/applyIdentityTopUpTransitionFactory.js
test/integration/identity/IdentityFacade.spec.js
test/unit/identity/stateTransitions/identityCreateTransition/applyIdentityCreateTransitionFactory.spec.js

`StateRepository` methods accept `Buffer` but there are still strings passed. 
Pass buffers to `StateRepositry` methods.
With tests.
None.

fix: strings passed to StateRepository instead of Buffers

---

lib/dataContract/DataContract.js
lib/document/Document.js
lib/identity/Identity.js
lib/identity/IdentityPublicKey.js
test/unit/identity/Identity.spec.js
test/unit/identity/IdentityPublicKey.spec.js
test/unit/identity/stateTransitions/identityCreateTransition/validateIdentityPublicKeyUniquenessFactory.spec.js

In order to hashes of data models without converting them to Buffer in many places that now accept buffers for binary data.
`hash` methods of models respond with `Buffer`
`hash` methods respond with `Buffer`

feat!: hash methods responds with Buffer

---

lib/dataContract/validateDataContractFactory.js
lib/test/fixtures/getDataContractFixture.js

Byte array properties were considered usual object and were not allowed to be valid indexed property.
Updated `validateDataContract` code
Unit tests - through updated fixtures.
None.

fix: byte array properties were not a valid indexed property

---

schema/dataContract/stateTransition/dataContractCreate.json
schema/document/stateTransition/documentTransition/create.json
test/integration/dataContract/stateTransition/validation/validateDataContractCreateTransitionStructureFactory.spec.js
test/integration/document/stateTransition/validation/structure/validateDocumentsBatchTransitionStructureFactory.spec.js

Entropy size in schemas is 20 to 35 instead of 32
Fixed schema to set entropy size to 32 bytes
Tests
No

fix: wrong entropy size

---

lib/dataContract/enrichDataContractWithBaseSchema.js
lib/document/stateTransition/validation/structure/validateDocumentsBatchTransitionStructureFactory.js

The same ID prefix is used for different enriched schemas so due to Ajv cache the first enriched contract is used for all cases.
- Passed prefix for base data contract schema
- Set different bytes for different prefixes
With tests
None

fix: one ID prefix for all enriched contracts

---

lib/dataContract/stateTransition/DataContractCreateTransition.js
lib/document/stateTransition/DocumentsBatchTransition.js
lib/identity/stateTransitions/identityCreateTransition/IdentityCreateTransition.js
lib/identity/stateTransitions/identityTopUpTransition/IdentityTopUpTransition.js
lib/stateTransition/AbstractStateTransition.js
test/unit/dataContract/stateTransition/DataContractCreateTransition.spec.js
test/unit/document/stateTransition/DocumentsBatchTransition.spec.js
test/unit/identity/stateTransitions/identityCreateTransition/IdentityCreateTransition.spec.js
test/unit/identity/stateTransitions/identityTopUpTransition/IdentityTopUpTransition.spec.js

Added `getModifiedDataIds` methods to every state transition for the DAPI's SubscribeToStateTransitionResults endpoint.
- Added `getModifiedDataIds` to the `AbstractStateTransition` and all classes that extend it;
- Added `isDocumentStateTransition`, `isDocumentStateTransition` and `isDocumentStateTransition` to the `AbstractStateTransition`
- Added unit tests for the aforementioned methods
Through newly added unit tests
None

feat: get modified data ids from state transitions

---

lib/DashPlatformProtocol.js
lib/StateRepositoryInterface.js
lib/identity/stateTransitions/assetLock/proof/instant/validateInstantAssetLockProofStructureFactory.js
lib/stateTransition/StateTransitionFacade.js
lib/test/mocks/createStateRepositoryMock.js
test/integration/identity/stateTransition/assetLock/proof/instant/validateInstantAssetLockProofStructureFactory.spec.js
test/unit/DashPlatformProtocol.spec.js

Using `verifyInstantLock` method now to move things to the Drive's side
- Updated State Repository interface
- Updated `validateInstantAssetLockProofStructure` method
Unit tests
None

feat: use `verifyInstantLock` instead of `fetchSMLStore`

---

lib/DashPlatformProtocol.js
lib/ajv/createAjv.js
lib/ajv/injectRE2.js
lib/ajv/keywords/byteArray/addByteArrayKeyword.js
test/integration/dataContract/stateTransition/validation/validateDataContractCreateTransitionStructureFactory.spec.js
test/integration/dataContract/validateDataContractFactory.spec.js
test/integration/document/stateTransition/validation/structure/validateDocumentsBatchTransitionStructureFactory.spec.js
test/integration/document/validateDocumentFactory.spec.js
test/integration/identity/stateTransition/assetLockProof/chain/validateChainAssetLockProofStructureFactory.spec.js
test/integration/identity/stateTransition/assetLockProof/instant/validateInstantAssetLockProofStructureFactory.spec.js
test/integration/identity/stateTransition/identityCreateTransition/validateIdentityCreateTransitionStructureFactory.spec.js
test/integration/identity/stateTransition/identityTopUpTransition/validateIdentityTopUpTransitionStructureFactory.spec.js
test/integration/identity/validation/validateIdentityFactory.spec.js
test/integration/identity/validation/validatePublicKeysFactory.spec.js

The initialization will run every time we call initialize function
Modified initialize method to run only once per instance
No

feat: initialization will run only once

---

lib/Metadata.js
lib/dataContract/DataContract.js
lib/document/Document.js
lib/identity/Identity.js
test/integration/document/Document.spec.js
test/unit/Metadata.spec.js
test/unit/dataContract/DataContract.spec.js
test/unit/identity/Identity.spec.js

To be able to transfer metadata information with data itself additional field was added
- added `getMetadata` and `setMetadata` to `Document`, `DataContract` and `Identity` classes
Unit tests
None.

feat: add metadata to document, data contract and identity

---

lib/document/Document.js
lib/document/DocumentFactory.js
lib/identity/Identity.js
lib/identity/IdentityFactory.js
lib/stateTransition/AbstractStateTransition.js
lib/stateTransition/StateTransitionFactory.js
test/unit/dataContract/stateTransition/DataContractCreateTransition.spec.js
test/unit/document/Document.spec.js
test/unit/document/DocumentFactory.spec.js
test/unit/document/stateTransition/DocumentsBatchTransition.spec.js
test/unit/identity/Identity.spec.js
test/unit/identity/IdentityFactory.spec.js
test/unit/stateTransition/StateTransitionFactory.spec.js

Need to move protocol version information out from encoded data and prepend the binary format. This allows to change the serialization format and keep backward compatibility.
Modified `toBuffer` methods to encode data into new binary format.
Unit tests
Previously serialized data is not compatible.

feat!: prepend protocol version for binary format

---

lib/dataContract/DataContract.js
lib/dataContract/DataContractFactory.js
test/unit/dataContract/DataContract.spec.js
test/unit/dataContract/DataContractFactory.spec.js

Fixing missing `protocolVersion` that should've been prepended in `toBuffer` of `DataContract` in following PR (#325)
- prepend `protocolVersion ` in `toBuffer` of `DataContract`
Unit tests
- Previously serialized data is not compatible.

fix!: protocol version was missing from binary data for data contract

---

lib/test/mocks/createDPPMock.js

DPP mock uses old stateTransition method names
`dppMock.stateTransition.validateData` renamed to `dppMock.stateTransition.validateState`
`dppMock.stateTransition.validateStructure` renamed to `dppMock.stateTransition.validateBasic`
Unit tests
No

test: dpp mock uses old stateTransition methods

---

lib/dataContract/validation/validateDataContractFactory.js
lib/test/fixtures/getDataContractFixture.js
test/integration/dataContract/validation/validateDataContractFactory.spec.js

DPP throws an error when you try to use index on arrays using prefixItems keyword #275 
No

fix: building indices on arrays using prefixItems

---

lib/version/protocolVersion.js

Add temporary protocol version 2 to conduct a test on the upgrade process.
- Bump protocol version to 2
With tests
None

chore: bump temporary protocol version
